### ISSUE TITLE
Block Durability

### ISSUE THREAD

**Issue by AlmondAppleSauce** [SpillereNO/BlowableObsidians#14]
Is there any way to change the percent to a number? Ex. Durability: 3/3

**Comment by anzure** [comment]
I guess I could make it so it rounds off to closest number in chosen range (1-3).
But the way it works now, is that it receive damage based on how close the explosion center is.

**Comment by AfkF24** [comment]
I would like to see this as well. Would basically mean that a block requires exactly X explosions to be destroyed.

**Comment by anzure** [comment]
This is actually implemented into version 6.3, but I would recommend waiting for version 6.4.
