### ISSUE TITLE
Block damage stuck at 80%

### ISSUE THREAD

**Issue by aces52s** [SpillereNO/BlowableObsidians#15]
Hi,

When damaged by TNT or creeper egg explosion blocks reduce health to 80% upon first explosion (health set to 5.0 so this is correct) however will not go any lower with subsequent explosions.

Using the default config on 1.8.8.

**Comment by AfkF24** [comment]
I'm actually experiencing a similar issue where it wouldn't go below 60%, also running the default config. Paper 1.15.2 build 229.

**Comment by AfkF24** [comment]
Just for further clarification, it seems that only the latest version has this issue.

**Comment by anzure** [comment]
I think this can be a bug related to the new health regeneration calculation.
I will look into this asap, in the meantime use verison 6.2.

However weird it worked perfectly for me and two other testers.

**Comment by Zodiak42** [comment]
Doesn't work either with me. Switched back to 6.2 and everything went fine again.

I am using the latest Paper 1.8 build, Ubuntu Server 19.10, OpenJDK 8u252 and running under a Bungeecord proxy.
