### ISSUE TITLE
[new] blowable with item

### ISSUE THREAD

**Issue by FyFou57** [SpillereNO/BlowableObsidians#18]
Being able to lower the hp with the tnt (or explosion) is good, but being able to do it with an item would be very good too, it would add a very interesting feature

blowable_item:
   ITEM_name_ONE:
      item : NETHER_STAR
      maxuse: 5
      hp_remove: 2

   ITEM_name_two:
      item : STRING
      maxuse: 15
      hp_remove: 1

and more..

blowable_item_lore:
- &cThis item remove %number% hp
- &aby utilisation, 
- Restant use : &e%use%/Max use :&d%maxuse% 

So the nether star will remove 2HP from the blowable block I target, and after 5 uses my nether star will "destroy" (delete)

**Comment by anzure** [comment]
Thanks for you suggetion.
I will consider creating this feature

**Comment by anzure** [comment]
I am sorry to inform you that I will not implement this feature in the near future.
