### ISSUE TITLE
Block's health with hologram

### ISSUE THREAD

**Issue by EternalHittMan** [SpillereNO/BlowableObsidians#20]
Instead of seeing the health of the blocks with the item, it would be nice to create holograms showing the health on the blocks after the explosion.

**Comment by anzure** [comment]
Hi.
Sorry, I will not implement this feature. It's too much work and not performance-friendly.

**Comment by EternalHittMan** [comment]
Ok. maybe it would be good to give a glow effect according to the health of the blocks. ex. red, yellow and green.
