### ISSUE TITLE
World Guard Bug

### ISSUE THREAD

**Issue by EternalHittMan** [SpillereNO/BlowableObsidians#22]
Worldguard support must be added to the plugin. Because, although the explosions are closed in a certain area, the blocks continue to break.  It also needs to be  disable feature in certain worlds.

**Comment by anzure** [comment]
I agree that it should be possible to disable this plugin in certain worlds, and I will implement that feature.

If the explosion is cancelled by another plugin, BlowableObsidians will not react nor damage any blocks. Are you sure that explosions are disabled in the WorldGuard-region?
