### ISSUE TITLE
Weird Nuke 

### ISSUE THREAD

**Issue by Hallontutten** [SpillereNO/BlowableObsidians#23]
Yo! I tested ur plugin and it left me with a really Strange looking nuke. Used 255 eff nuke. The nuke went horizontal and createad holes in that line. Using ElapsedSpigot

**Comment by anzure** [comment]
Hi, thank you for reporting this.
May I ask if you have a picture or pictures of this?
I should be able to fix this then.

**Comment by anzure** [comment]
No response from issuer, closing issue.
