### ISSUE TITLE
Movecraft compatibility

### ISSUE THREAD

**Issue by Pvprod34** [SpillereNO/BlowableObsidians#26]
Hi! you couldn't add movecraft compatiblity could you any chance? a lot of servers use tnt/cannons alongside this plugin. Movecraft has block based moving ships. Currently if you move your ship the explosion damage resets or stay in that cordinate position... so if you fly off your protected block gets a new set of health.

**Comment by anzure** [comment]
Sorry, I suspect this may be too much of work.
