### ISSUE TITLE
Setting for liquid multiplier does not seem to be working. running 1.16.4

### ISSUE THREAD

**Issue by Dschopopp** [SpillereNO/BlowableObsidians#27]
Blocks wont explode in water even with liquid multiplier set.

**Comment by Dschopopp** [comment]
Nvm I think I understand. I a little confused on how to configure the wild card <blocks> section

**Comment by Dschopopp** [comment]
Solved. Sorry about that!

**Comment by anzure** [comment]
Glad it works for you 👍
