### ISSUE TITLE
MMOItems Custom Block Support

### ISSUE THREAD

**Issue by SpiralOfRegret** [SpillereNO/BlowableObsidians#28]
Wondering if you could add support for mmoitems, which has a feature that allows you to create custom blocks with custom textures. If you could make it so that you can add custom health based on the mmoitem block id rather than the material that would be a great feature. Adding the feature to give custom damage for custom tnt based on block id would also be a great feature.

**Comment by anzure** [comment]
Thanks for your suggestion, I will look into this possibility later.

**Comment by anzure** [comment]
I am sorry to inform you that I will not implement this feature in the near future.
