### ISSUE TITLE
BUG Fix/Feature Request

### ISSUE THREAD

**Issue by GodKiko123** [SpillereNO/BlowableObsidians#32]
Please help me, your plugin is fantastic, but there are two problems.

1 - The armor stands are not exploding! (Please fix this as soon as possible).

2 - Is there any possibility for you to improve the performance that your plugin has on my server? I'm having a pretty big drop in TPS when big cannons explode there.
Thanks,
GodKiko123

**Comment by anzure** [comment]
1. Armor Stands is technically not blocks. It is rendered as an entity.
So I don't think it will be beneficial to implement a fix for this.

2. I will attempt to find ways to improve the performance.
Thank you for bringing this to my attention.

**Comment by GodKiko123** [comment]
1. Would it be possible to add this function?
Type an option in the configuration that you toggle if you want the armor to explode or not... I can even pay you to have this function I can't find anywhere, something that does that... If necessary we can say a value so that adds this "toggle" option to the armatures.

2. Thank you very much, your plugin is essential on my server.

Stay safe,
GodKiko123

**Comment by anzure** [comment]
1. It is possible to add this function. However, it might decrease the TPS a bit.
If you still want this, I can probably do a developer job for you.
This will probably take 5-10 hours to develop including testing.
You may contact me at andre@odit.no to discuss price.

2. Optimal performance is very important. Glad you appreciate my plugin.
