### ISSUE TITLE
Bedrock Keeps coming back

### ISSUE THREAD

**Issue by APonder-Dev** [SpillereNO/BlowableObsidians#37]
The plugin works on obsidian but when I go to add bedrock to the destroyed block. What happens is that it causes a ghost block to form, and unless you either update the area or leave. The Bedrock respawns at full health. This is an issue for my server causing bases to be unraidable.
[versions.txt](https://github.com/SpillereNO/BlowableObsidians/files/9440660/versions.txt)

**Comment by APonder-Dev** [comment]
This server is running Pufferfish version git-Pufferfish-72 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8f05a00 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-69 (MC: 1.18.2)

**Comment by Anzure** [comment]
Sounds like an easily solvable bug, I will do this when I have time.

**Comment by Anzure** [comment]
Please check out this, it might be a temporary workaround:
https://github.com/SpillereNO/BlowableObsidians/issues/34

**Comment by APonder-Dev** [comment]
Okie Ill look into this

**Comment by APonder-Dev** [comment]
Thank you this fixed the issue, sorry for not responding sooner. Got busy with alot of things
