### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by hetjoshi** [SpillereNO/BlowableObsidians#8]
Ok I enabled only tnt to true, when I charge a creeper with /lightning while on top of a obsidian block, it doesnt take damage HOWEVER after doing it like 2-3 times the obsidian disspears for some reason. PLEASE TRY IT, THIS IS ACTUAL BUG.

**Comment by hetjoshi** [comment]
edit: its not just charged creeper, its regular creepers as well :/

**Comment by anzure** [comment]
Try latest version now 😊
